### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by veggiemonk** [EwenG/replique#1]
Sorry to ask such a simple thing, but if you could help me to test it I would appreciate it.

Thanks in advance

**Comment by EwenG** [comment]
Hi veggiemonk,
Replique requires the use of a client. At the moment, the only client available is https://github.com/EwenG/replique.el

**Comment by veggiemonk** [comment]
Ok thanks.

**Comment by EwenG** [comment]
For the record, I updated the README to show the use of Replique from a terminal

**Comment by veggiemonk** [comment]
great thanks a lot. 👍
